import { useEffect, useRef, type ReactNode } from "react"
const photos=["https://images.unsplash.com/photo-1578344147728-e2ad1d7a66eb?auto=format&fit=crop&w=1800&q=85","https://images.unsplash.com/photo-1765334666990-1bf2ce733864?auto=format&fit=crop&w=1400&q=85","https://images.unsplash.com/photo-1542743866-c49833265fdc?auto=format&fit=crop&w=1400&q=85"]
function Reveal({children,className=""}:{children:ReactNode,className?:string}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting){el.classList.add("show");o.unobserve(el)}},{threshold:.12});o.observe(el);return()=>o.disconnect()},[]);return <div ref={ref} className={`reveal ${className}`}>{children}</div>}
const work=[['01','COMMON GROUND','IDENTITY / CAMPAIGN / DIGITAL'],['02','NO FILTER','ART DIRECTION / EDITORIAL'],['03','INTO THE UNKNOWN','BRAND WORLD / EXPERIENCE']]
export default function App(){useEffect(()=>{const move=(e:PointerEvent)=>{document.documentElement.style.setProperty('--x',`${e.clientX}px`);document.documentElement.style.setProperty('--y',`${e.clientY}px`)};addEventListener('pointermove',move);return()=>removeEventListener('pointermove',move)},[]);return <main>
<div className="grain"/><div className="glow"/>
<header><a className="logo" href="#top">ODD<span>—</span>ITY</a><small>INDEPENDENT CREATIVE STUDIO<br/>LONDON / EVERYWHERE</small><nav><a href="#work">WORK</a><a href="#studio">STUDIO</a><a href="#contact">CONTACT</a></nav></header>
<section className="hero" id="top"><div className="circle"/><h1><i>WE MAKE</i><i className="red">*BRANDS</i><i>UNMISSABLE.</i></h1><div className="intro"><p>A fiercely independent creative studio building brave identities, culture-shifting campaigns and digital worlds.</p><a className="cta" href="#work">SEE WHAT WE DO <b>↗</b></a></div></section>
<div className="ticker"><div>BRAND STRATEGY ✳ VISUAL IDENTITY ✳ CAMPAIGNS ✳ DIGITAL EXPERIENCES ✳ BRAND STRATEGY ✳ VISUAL IDENTITY ✳ CAMPAIGNS ✳ DIGITAL EXPERIENCES ✳</div></div>
<section className="work" id="work"><Reveal className="headline"><small>(01) SELECTED WORK</small><h2>BUILT TO <em>MOVE</em><br/>PEOPLE.</h2><p>Not decoration. Not noise. Work with a point of view and a pulse.</p></Reveal>
<div className="projects">{work.map((p,i)=><Reveal className="project" key={p[0]}><a href="#contact"><div className="visual"><img src={photos[i]} alt={i===0?'Red and blue geometric architecture':i===1?'Colorful editorial portrait':'Concrete spiral structure'}/><b>VIEW CASE ↗</b></div><div className="meta"><small>{p[0]}</small><h3>{p[1]}</h3><small>{p[2]}</small></div></a></Reveal>)}</div></section>
<section className="studio" id="studio"><div className="studioPic"><img src="https://images.unsplash.com/photo-1713982154438-e411b95917a2?auto=format&fit=crop&w=1600&q=85" alt="Colorful modernist building"/><b>NO BLAND<br/>BRANDS</b></div><Reveal className="studioCopy"><small>(02) OUR STUDIO</small><h2>SMALL TEAM.<br/><em>BIG ENERGY.</em></h2><div><p>We are strategists, designers, makers and restless thinkers. We partner with ambitious people who want to make a meaningful dent in the world.</p><p>No layers. No hand-offs. Just senior talent, honest conversation and an unreasonable level of care.</p></div><a className="cta pale" href="#contact">MEET THE COLLECTIVE <b>↗</b></a></Reveal></section>
<section className="principles"><small>(03) THE WAY WE WORK</small>{['START WITH A SHARP QUESTION','MAKE THE STRANGE FEEL RIGHT','DESIGN FOR REAL HUMAN BEINGS','NEVER SETTLE FOR JUST FINE'].map((x,i)=><Reveal className="rule" key={x}><small>0{i+1}</small><h3>{x}</h3><b>↗</b></Reveal>)}</section>
<footer id="contact"><div className="footTop"><small>(04) GET IN TOUCH</small><span>HAVE A GOOD PROBLEM?</span></div><h2>LET'S MAKE<br/><em>SOMETHING</em><br/>BRILLIANT.</h2><a className="email" href="mailto:hello@oddity.studio">hello@oddity.studio <b>↗</b></a><div className="bottom"><span>© ODDITY STUDIO 2025</span><span>INSTAGRAM &nbsp; LINKEDIN &nbsp; BEHANCE</span><span>LONDON / 51.5072° N</span></div></footer>
</main>}
